creation_rules:
    - key_groups:
          - age:
                - age1l5h0zjpjjgf3awxwf2r9ufepvd7el6nh3c7l6welg5u79eajn5vs7ggz5j
                - age1ttqv8dw6r94hdgf975r0vq45eq7cr2dx9w7w3dl7y78lstk5hvlsdavtxr
