name: "pre-commit"
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  conform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Conform Action
        uses: siderolabs/conform@v0.1.0-alpha.29
